import Head from 'next/head'
import Post from '../components/Post';
import styles from '../styles/Home.module.css'
import Container from 'react-bootstrap/Container';

import 'bootstrap/dist/css/bootstrap.min.css';

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/post?amt=5`)
  const posts = await res.json()

  return { props: { posts } }
}

export default function Home({posts}) {
  const comPosts = posts.map((post) => {
    return <Post 
      user={post.user} 
      title={post.title} 
      body={post.body}
      avatar={post.avatar}
      email={post.email}
      date={post.date}
    ></Post>
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Reacttir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container fluid>
        <h1 class="text-center">Fake Twitter</h1>
      </Container>

      {comPosts}
    </div>
  )
}
